<?php
/**
 * The catalogue's tables, modelled with MySQL's semantics for EXACTLY the
 * statements CashFlow_Catalog::sql() builds. Each statement's expected text is
 * held here as a LITERAL string (below, in SQL) — this file never calls
 * CashFlow_Catalog::sql() to learn what to expect. A statement is recognised
 * only by matching that literal, so if the plugin's SQL changes — including a
 * wrong constant such as SET_STATUSES baked into the text — this model does
 * not silently follow along: the statement goes unrecognised and throws. It
 * is never "executed" by a guess, and it can never certify a bug the two
 * sides happen to share.
 *
 * catalogQueueMysql.test.php runs the same scenarios on a real MySQL; that is
 * what proves this model honest.
 */
class CF_Test_CatalogDB {

    /** Which $wpdb method each statement must arrive through. */
    const METHODS = [
        'show_table' => 'get_var', 'insert' => 'query', 'insert_set' => 'query',
        'claim_real' => 'query', 'claim_any' => 'query', 'claim_listed' => 'query', 'select_claimed' => 'get_results',
        'done' => 'query', 'release_failed' => 'query', 'release_untried' => 'query', 'park' => 'query',
        'clear_parked' => 'query', 'count_pending' => 'get_var', 'count_parked' => 'get_var',
        'parked_ids' => 'get_col', 'enumerate' => 'get_col', 'exists_listed' => 'get_col',
    ];

    // The exact text CashFlow_Catalog::sql() must produce, on the table names
    // this harness's $wpdb reports (prefix 'wp_', posts 'wp_posts'). Written
    // out by hand from the plugin's own templates, not generated by calling
    // them — a generated copy would agree with a wrong constant by construction.
    const SQL = [
        'show_table'      => 'SHOW TABLES LIKE %s',
        'insert'          => 'INSERT IGNORE INTO wp_cashflow_catalog_queue (product_id, reason, attempts, queued_at, pending_key) VALUES (%d, %s, 0, %s, %s)',
        'insert_set'      => "INSERT IGNORE INTO wp_cashflow_catalog_queue (product_id, reason, attempts, queued_at, pending_key) SELECT ID, 'resend', 0, %s, CONCAT(ID, ':resend') FROM wp_posts WHERE post_type = 'product' AND post_status IN ('publish', 'future', 'draft', 'pending', 'private')",
        'claim_real'      => "UPDATE wp_cashflow_catalog_queue SET attempts = attempts + IF(token IS NULL, 0, 1), token = %s, claimed_at = %s, pending_key = NULL WHERE parked_at IS NULL AND (token IS NULL OR claimed_at < %s) AND (retry_at IS NULL OR retry_at <= %s) AND reason IN ('save', 'removed') ORDER BY id ASC LIMIT %d",
        'claim_any'       => "UPDATE wp_cashflow_catalog_queue SET attempts = attempts + IF(token IS NULL, 0, 1), token = %s, claimed_at = %s, pending_key = NULL WHERE parked_at IS NULL AND (token IS NULL OR claimed_at < %s) AND (retry_at IS NULL OR retry_at <= %s) ORDER BY (reason IN ('asked', 'resend')) ASC, id ASC LIMIT %d",
        'select_claimed'  => 'SELECT id, product_id, reason, attempts FROM wp_cashflow_catalog_queue WHERE token = %s ORDER BY id ASC',
        'done'            => 'DELETE FROM wp_cashflow_catalog_queue WHERE id = %d AND token = %s',
        'release_failed'  => "UPDATE IGNORE wp_cashflow_catalog_queue SET attempts = attempts + 1, token = NULL, claimed_at = NULL, retry_at = %s, pending_key = CONCAT(product_id, ':', reason) WHERE id = %d AND token = %s",
        'release_untried' => "UPDATE IGNORE wp_cashflow_catalog_queue SET token = NULL, claimed_at = NULL, pending_key = CONCAT(product_id, ':', reason) WHERE id = %d AND token = %s",
        'park'            => 'UPDATE wp_cashflow_catalog_queue SET attempts = %d, token = NULL, claimed_at = NULL, pending_key = NULL, parked_at = %s WHERE id = %d AND token = %s',
        'clear_parked'    => 'DELETE FROM wp_cashflow_catalog_queue WHERE product_id = %d AND parked_at IS NOT NULL',
        'count_pending'   => 'SELECT COUNT(*) FROM wp_cashflow_catalog_queue WHERE parked_at IS NULL',
        'count_parked'    => 'SELECT COUNT(*) FROM wp_cashflow_catalog_queue WHERE parked_at IS NOT NULL',
        'parked_ids'      => 'SELECT product_id FROM wp_cashflow_catalog_queue WHERE parked_at IS NOT NULL ORDER BY id ASC LIMIT 20',
        'enumerate'       => "SELECT ID FROM wp_posts WHERE post_type = 'product' AND post_status IN ('publish', 'future', 'draft', 'pending', 'private') AND ID > %d ORDER BY ID ASC LIMIT %d",
    ];

    // claim_listed and exists_listed both embed {ids} as a literal CSV of
    // ints straight in the SQL text — a runtime-variable list, unlike every
    // other {…} placeholder here (SET_STATUSES never changes), so neither
    // can be ONE fixed literal in SQL above. Recognised instead by the exact
    // literal text either SIDE of that one variable list: any deviation in
    // either fixed part still fails to match, the same guarantee SQL gives
    // everywhere else — only the ids themselves are unconstrained, and even
    // those must be a plain digit/comma list or this refuses to recognise it.
    const CLAIM_LISTED_PREFIX  = 'UPDATE wp_cashflow_catalog_queue SET attempts = attempts + IF(token IS NULL, 0, 1), token = %s, claimed_at = %s, pending_key = NULL WHERE parked_at IS NULL AND (token IS NULL OR claimed_at < %s) AND (retry_at IS NULL OR retry_at <= %s) AND product_id IN (';
    const CLAIM_LISTED_SUFFIX  = ') ORDER BY id ASC LIMIT %d';
    const EXISTS_LISTED_PREFIX = 'SELECT DISTINCT product_id FROM wp_cashflow_catalog_queue WHERE product_id IN (';
    const EXISTS_LISTED_SUFFIX = ') AND parked_at IS NULL';

    /** The ids literally embedded between a listed statement's fixed prefix and suffix. */
    private static function listed_ids( string $sql, string $prefix, string $suffix ): array {
        $middle = substr( $sql, strlen( $prefix ), -strlen( $suffix ) );
        if ( ! preg_match( '/^[0-9]+(,[0-9]+)*$/', $middle ) ) {
            throw new RuntimeException( 'harness: a listed statement\'s ids were not a plain digit list: ' . $sql );
        }
        return array_map( 'intval', explode( ',', $middle ) );
    }

    public static function name_of( string $sql ): ?string {
        $name = array_search( $sql, self::SQL, true );
        if ( false !== $name ) {
            return $name;
        }
        if ( str_starts_with( $sql, self::CLAIM_LISTED_PREFIX ) && str_ends_with( $sql, self::CLAIM_LISTED_SUFFIX ) ) {
            return 'claim_listed';
        }
        if ( str_starts_with( $sql, self::EXISTS_LISTED_PREFIX ) && str_ends_with( $sql, self::EXISTS_LISTED_SUFFIX ) ) {
            return 'exists_listed';
        }
        return null;
    }

    public static function run( string $method, string $name, array $a, $wpdb, string $sql = '' ) {
        CF_TestState::$sql[] = 'catalog:' . $name;
        if ( ( self::METHODS[ $name ] ?? null ) !== $method ) {
            throw new RuntimeException( "harness: catalogue statement $name must not arrive through \$wpdb->$method" );
        }
        if ( null !== CF_TestState::$db_error_on && str_contains( $sql, CF_TestState::$db_error_on ) ) {
            $wpdb->last_error = 'harness: injected failure in ' . $name;
            return 'query' === $method ? false : ( 'get_var' === $method ? null : [] );
        }
        // Fails from the Nth call to this statement onward — lets a test put
        // a REAL success before a failure (e.g. enumerate()'s first CHUNK
        // succeeds, a later one does not), which a single global switch
        // cannot express [task-12].
        CF_TestState::$stmt_call_counts[ $name ] = ( CF_TestState::$stmt_call_counts[ $name ] ?? 0 ) + 1;
        $call_n = CF_TestState::$stmt_call_counts[ $name ];
        if ( isset( CF_TestState::$stmt_fail_from_call[ $name ] ) && $call_n >= CF_TestState::$stmt_fail_from_call[ $name ] ) {
            $wpdb->last_error = 'harness: injected failure in ' . $name . ' (call ' . $call_n . ')';
            return 'query' === $method ? false : ( 'get_var' === $method ? null : [] );
        }
        // A HARNESS-ONLY silent failure: returns a non-array (`false`) with
        // $wpdb->last_error left UNSET, so a caller must catch it on the
        // return SHAPE alone rather than on last_error. Corrected per
        // review [task-12, minor]: this is NOT a real \wpdb::get_col()
        // behaviour — that method always returns an ARRAY, even on
        // failure (typically `[]`, with last_error also left empty on some
        // failure modes) — it exists purely to exercise enumerate()'s
        // `! is_array($ids)` branch in isolation. It does not model, and
        // must not be described as covering, the realistic
        // "not-ready-connection" case (an empty array, no last_error).
        if ( $name === CF_TestState::$db_silent_failure_on ) {
            return false;
        }
        $q = &CF_TestState::$catalog_queue;
        switch ( $name ) {
            case 'show_table':
                return isset( CF_TestState::$catalog_tables[ $a[0] ] ) ? $a[0] : null;

            case 'insert':
                return self::insert( (int) $a[0], (string) $a[1], (string) $a[2], (string) $a[3] );

            case 'insert_set':
                $n = 0;
                foreach ( self::set_ids( 0, PHP_INT_MAX ) as $id ) {
                    $n += self::insert( $id, 'resend', (string) $a[0], $id . ':resend' );
                }
                return $n;

            case 'claim_real':
            case 'claim_any':
            case 'claim_listed':
                [ $token, $at, $stale_before, $now, $limit ] = $a;
                $listed = 'claim_listed' === $name ? self::listed_ids( $sql, self::CLAIM_LISTED_PREFIX, self::CLAIM_LISTED_SUFFIX ) : [];
                $due = [];
                foreach ( $q as $r ) {
                    if ( null !== $r['parked_at'] ) { continue; }
                    if ( null !== $r['token'] && ! ( $r['claimed_at'] < $stale_before ) ) { continue; }
                    if ( null !== $r['retry_at'] && ! ( $r['retry_at'] <= $now ) ) { continue; }
                    if ( 'claim_real' === $name && ! in_array( $r['reason'], [ 'save', 'removed' ], true ) ) { continue; }
                    if ( 'claim_listed' === $name && ! in_array( (int) $r['product_id'], $listed, true ) ) { continue; }
                    $due[] = $r;
                }
                usort( $due, function ( $x, $y ) use ( $name ) {
                    if ( 'claim_any' === $name ) {
                        $d = (int) in_array( $x['reason'], [ 'asked', 'resend' ], true ) <=> (int) in_array( $y['reason'], [ 'asked', 'resend' ], true );
                        if ( 0 !== $d ) { return $d; }
                    }
                    return (int) $x['id'] <=> (int) $y['id'];
                } );
                $n = 0;
                foreach ( array_slice( $due, 0, (int) $limit ) as $r ) {
                    $id = (int) $r['id'];
                    // MySQL evaluates SET left to right: attempts reads the OLD token.
                    $q[ $id ]['attempts']    = (string) ( (int) $q[ $id ]['attempts'] + ( null === $q[ $id ]['token'] ? 0 : 1 ) );
                    $q[ $id ]['token']       = (string) $token;
                    $q[ $id ]['claimed_at']  = (string) $at;
                    $q[ $id ]['pending_key'] = null;
                    $n++;
                }
                return $n;

            case 'select_claimed':
                $out = [];
                foreach ( $q as $r ) {
                    if ( $r['token'] === (string) $a[0] ) {
                        $out[] = [ 'id' => $r['id'], 'product_id' => $r['product_id'], 'reason' => $r['reason'], 'attempts' => $r['attempts'] ];
                    }
                }
                usort( $out, function ( $x, $y ) { return (int) $x['id'] <=> (int) $y['id']; } );
                return $out;

            case 'done':
                $id = (int) $a[0];
                if ( isset( $q[ $id ] ) && $q[ $id ]['token'] === (string) $a[1] ) { unset( $q[ $id ] ); return 1; }
                return 0;

            case 'release_failed':
            case 'release_untried':
                [ $id, $token ] = 'release_failed' === $name ? [ (int) $a[1], (string) $a[2] ] : [ (int) $a[0], (string) $a[1] ];
                if ( ! isset( $q[ $id ] ) || $q[ $id ]['token'] !== $token ) { return 0; }
                $key = $q[ $id ]['product_id'] . ':' . $q[ $id ]['reason'];
                foreach ( $q as $other ) {
                    if ( $other['pending_key'] === $key ) { return 0; }   // UPDATE IGNORE: duplicate key, row skipped
                }
                if ( 'release_failed' === $name ) {
                    $q[ $id ]['attempts'] = (string) ( (int) $q[ $id ]['attempts'] + 1 );
                    $q[ $id ]['retry_at'] = (string) $a[0];
                }
                $q[ $id ]['token'] = null;
                $q[ $id ]['claimed_at'] = null;
                $q[ $id ]['pending_key'] = $key;
                return 1;

            case 'park':
                [ $attempts, $at, $id, $token ] = [ (int) $a[0], (string) $a[1], (int) $a[2], (string) $a[3] ];
                if ( ! isset( $q[ $id ] ) || $q[ $id ]['token'] !== $token ) { return 0; }
                $q[ $id ] = array_merge( $q[ $id ], [ 'attempts' => (string) $attempts, 'token' => null, 'claimed_at' => null,
                    'pending_key' => null, 'parked_at' => $at ] );
                return 1;

            case 'clear_parked':
                $n = 0;
                foreach ( $q as $id => $r ) {
                    if ( (int) $r['product_id'] === (int) $a[0] && null !== $r['parked_at'] ) { unset( $q[ $id ] ); $n++; }
                }
                return $n;

            case 'count_pending':
                return (string) count( array_filter( $q, function ( $r ) { return null === $r['parked_at']; } ) );

            case 'count_parked':
                return (string) count( array_filter( $q, function ( $r ) { return null !== $r['parked_at']; } ) );

            case 'parked_ids':
                $parked = array_values( array_filter( $q, function ( $r ) { return null !== $r['parked_at']; } ) );
                usort( $parked, function ( $x, $y ) { return (int) $x['id'] <=> (int) $y['id']; } );
                return array_map( function ( $r ) { return $r['product_id']; }, array_slice( $parked, 0, 20 ) );

            case 'enumerate':
                return array_map( 'strval', self::set_ids( (int) $a[0], (int) $a[1] ) );

            case 'exists_listed':
                $ids = self::listed_ids( $sql, self::EXISTS_LISTED_PREFIX, self::EXISTS_LISTED_SUFFIX );
                $present = array_unique( array_map( function ( $r ) { return (int) $r['product_id']; },
                    array_filter( $q, function ( $r ) use ( $ids ) { return in_array( (int) $r['product_id'], $ids, true ) && null === $r['parked_at']; } ) ) );
                sort( $present );
                return array_map( 'strval', array_values( $present ) );
        }
        throw new RuntimeException( "harness: catalogue statement $name not modelled" );
    }

    private static function insert( int $product_id, string $reason, string $at, string $key ): int {
        foreach ( CF_TestState::$catalog_queue as $r ) {
            if ( $r['pending_key'] === $key ) { return 0; }         // INSERT IGNORE: duplicate key
        }
        $id = CF_TestState::$catalog_queue_next++;
        CF_TestState::$catalog_queue[ $id ] = [
            'id' => (string) $id, 'product_id' => (string) $product_id, 'reason' => $reason, 'token' => null,
            'attempts' => '0', 'queued_at' => $at, 'claimed_at' => null, 'retry_at' => null, 'parked_at' => null,
            'pending_key' => $key,
        ];
        return 1;
    }

    /** wp_posts: products in the set, id > $after, ascending. */
    private static function set_ids( int $after, int $limit ): array {
        $ids = [];
        foreach ( CF_TestState::$posts as $id => $p ) {
            if ( 'product' === $p['type'] && in_array( $p['status'], [ 'publish', 'future', 'draft', 'pending', 'private' ], true ) && (int) $id > $after ) {
                $ids[] = (int) $id;
            }
        }
        sort( $ids );
        return array_slice( $ids, 0, $limit );
    }
}
